---
# tasks file for ansible-arch-xorg

- name: Make sure xorg packages are present
  pacman:
    name: '{{ item }}'
    state: present
  loop:
    - xorg
    - xorg-server
    - xorg-apps
    - xorg-xinit

- name: Make sure 00-keyboard.conf is set to the german keyboard layout
  template:
    src: 00-keyboard.j2
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: 0644
